version: "3.9"

services:
  node-app:
    build: ./website
    container_name: "${DOCKSITE_CONTAINER_NAME}_frontend"
    ports:
      - "3000:3000"

  flask-app:
    build: ./backend
    container_name: "${DOCKSITE_CONTAINER_NAME}_backend"
    ports:
      - "5000:5000"